vinicius-arroyo/myt-shard

sphere_56b/trunk/scripts/myt/quests.scp

Adicionados: i_trava_portas; i_dismount; i_simbolo_abencoado; i_simbolo_maldito; i_simbolo_protecao_divina; i_movedor; i_empurrador; i_correnteza; i_transportador

Adição de 9 itemdefs

---

sphere_56b/trunk/scripts/myt/sistema_de_facas_especiais.scp

Correção da Linha que estava documentando errado
Adição de itemdefs de facas especiais

Correção da linha 360 e adição de 3 itemdefs

---

sphere_56b/trunk/scripts/myt/sistema_de_armadilha.scp

Adição de i_trap_spike i_trap_spikes_hi i_trap_spikes_lo
Adição de i_trap_explosion i_trap_explosion_hi i_trap_explosion_lo
Adição de i_trap_poison i_trap_poison_hi i_trap_poison_lo
Adição de i_trap_cogumelo

Adição de traps craftaveis e cogumelo

---

sphere_56b/trunk/scripts/myt/itens.scp

extratos do itemforge demarcados no scp

Adição de vários itemdefs

---

sphere_56b/trunk/scripts/myt/skill_blacksmith.scp

Adição de i_alicate e i_trefila

Adição de Alicate e trefila

---

sphere_56b/trunk/scripts/myt/special/region.scp

Resources de pesca devem sempre ser itens t_fish, para serem cortados com facas para t_food_raw e então para ser componente de cozinha t_food.
i_fish_small que é recurso pesqueiro (t_fish)
i_fish_raw_small é componente de cozinha (t_food_raw)

Ajuste na Sardinha novamente

---

sphere_56b/trunk/scripts/myt/itens_quests.scp

Tile que gera msg ao ser pisado pelo player. Facilidade de edição pelo GM através de boxe de diálogo.

Adição de Tile de Msg on step

---

sphere_56b/trunk/scripts/myt/sistema_de_selar_livros.scp

Corrigido resources (pérola negra, frasco e pena), número de usos (3xpérola negra) e a skill (alchemy, pois envolve criação de solução química).

Tornando a i_pen_and_ink craftável

---

sphere_56b/trunk/scripts/myt/templates_myt.scp

Adicionando Recipes de Cooking para poder aparecer no loot.

Adicionando Recipes no Loot

---

sphere_56b/trunk/scripts/myt/sistema_de_receitas.scp

Organizando, atualizando e corrigindo Receitas de Cooking:
// i_recipe_pig_lumenor
// i_recipe_pig_moravia
// i_recipe_gemada_mu
// i_recipe_mexido_orc
// i_recipe_guisado_triade
// i_recipe_ovo_harpia_frito

4 Receitas de Cooking

---

sphere_56b/trunk/scripts/myt/npcs_humanoides.scp

Mudança da linha 5374 de Rodarik para Mestre Anão.

Mudança do nome de Rodarik para mestre Anão

---

sphere_56b/trunk/scripts/myt/itens.scp

Inserindo a possibilidade de enrolar/desenrolar o saco de dormir.

Saco de Dormir Enrolável

---

sphere_56b/trunk/scripts/myt/sistema_de_receitas.scp

Adicionados projetos para 
i_braco_furtiva
i_cabeca_furtiva
i_luva_furtiva
i_peito_furtiva
i_perna_furtiva
i_pescoco_furtiva

Adição de 6 Itens de Tailoring

---

sphere_56b/trunk/scripts/myt/templates_myt.scp

- Nerfada em loots mágicos no template de loot comum de DG's do shard, que não deveriam vir com itens mágicos e sim itens comuns;
- Nerfada no loot de pots e bandagens no template de provisões do shard;
- Nerfada no loot de trapos;
- Nerfada no loot dos piratas;

Uma bela nerfada em loots 

---

sphere_56b/trunk/scripts/myt/sistema_de_plantacao.scp

// Camping 00: alface, batata, cenoura, ervilha, milho;
// Camping 10: trigo e ginseng;
// Camping 20: alho, fumo, mandrágora;
// Camping 30: algodão, bananeira e macieira;
// Camping 40: sombra da noite, parreira.

Camping Mínimo para Cultivos

---

sphere_56b/trunk/scripts/myt/sistema_de_caldeirao.scp

Tornando possível fazer Whisky e Leite Onírico

Correções e Adição de 2 Novas Bebidas

---

sphere_56b/trunk/scripts/myt/npcs_humanoides.scp

Exclusão de templates de pirata e inclusão de novos itens nos MOBs.

Ajuste nos NPCs piratas

---

sphere_56b/trunk/scripts/myt/npcs.scp

Inversão do nome do Búfalo e do Bisão.

Alteração de Bufalo e Bisao

---

sphere_56b/trunk/scripts/myt/events_npc.scp

Correção do ATTR_CAN_DECAY para ATTR_DECAY

Correção do e_firemade

---

sphere_56b/trunk/scripts/myt/sistema_de_plantacao.scp

Correções de erros bobos de "itemdef" para "defname", remoção de <> do teste de if, e "sysmessared" para "sysmessaGEred". T.T que vacilo meu.

Correção de Sintaxe no Mínimo de Camping (testadas e ok)

---

sphere_56b/trunk/scripts/myt/itens_food.scp

Nove comidas criadas ingame:
i_sopao_galinha
i_pao_ovo
i_bolo_fuba
i_torta_coelho
i_omelete_especial
i_sausages_chiken_raw
i_sausages_chiken
i_carne_panela
i_mexilhao_gratinado

Comidas criadas (testadas e ok)

---

sphere_56b/trunk/scripts/myt/itens_tailor.scp

Ajustei o craft das mascaras de veado e urso para t_armor, bem como os maxhits das mesmas.
Setado pra no máximo 600 de resist.

Acerto no craft das mascaras de veado e urso

---

sphere_56b/trunk/scripts/myt/itemforge_data_armaduras_armas.scp

Alteração de Prefixo DMG para DAM
dmgcold - damcold
dmgfire - damfire
dmgenergy - damenergy
dmgpoison - dampoison
Testado previamente no meu sphere.

Fix de Danos Elementais

---

sphere_56b/trunk/scripts/myt/skill_tinkering.scp

Alteração na Capacidade de Carga do Baú Enfeitado para acompanhar os outros containers do Shard e alteração nos resources e skillmake para balancear com a alteração.

Alteração na Capacidade de Carga do Baú Enfeitado

---

sphere_56b/trunk/scripts/myt/itens_carpentry.scp

Ajuste da capacidade de carga de acordo com os containers do shard (e correções de nomes ultrapassados).

Ajuste de Capacidade de Carga

---

sphere_56b/trunk/scripts/myt/itens_tailor.scp

Há um item em algum lugar duplicado, eu mudei o nome do item para i_mascara_cervo para arrumar isso.

Mascara de Veado

---

sphere_56b/trunk/scripts/myt/itemforge_data_tailoring.scp

Item removido, estava em duplicidade.

Removido mascara de veado para evitar conflito

---

sphere_56b/trunk/scripts/myt/npcs.scp

Adicionado loot em formiga rainha.

Adicionado loot em mob

---

sphere_56b/trunk/scripts/myt/sistema_de_selar_livros.scp

Livros podem ser encriptados em um determinado idioma.

(Testado e OKtoUP) - Implementação do Sistema de Idiomas

---

sphere_56b/trunk/scripts/myt/sistema_de_selar_livros.scp

Da maneira que estava, plevel 1 não conseguia executar o comando. Vejamos se assim vai.

Ajuste mínimo para ver se vai

---

sphere_56b/trunk/scripts/myt/itens_food.scp

Dispensando craftool para fazer linguiça crua, passando a ser possível fazer com dclick na i_entranhas

Novo esquema para fazer Linguiças

---

sphere_56b/trunk/scripts/myt/skill_musicianship.scp

Sugestão do US: Transferindo o IF <src.findid.i_meditation> para a function BARDSONG_TEST

Ajuste de Meditation

---

sphere_56b/trunk/scripts/myt/sistema_de_tempo.scp

Adicionando resources e skillmake para termômetro (que tem projeto em loot) tornar-se craftável.

Ajuste em Termometro

---

sphere_56b/trunk/scripts/myt/sistema_de_catalisadores.scp

Poste Ornado que testa de 10 em 10 minutos se é dia ou noite. Se não for dia, acende.

Adição de Iluminação Pública

---

sphere_56b/trunk/scripts/myt/sistema_de_portos.scp

Ajuste para evitar que guardas e vendedores desgovernados possam embarcar no i_embarque
Ajuste para que animais acompanhando seus donos possam desembarcar.

Melhorias de Uso

---

sphere_56b/trunk/scripts/myt/sistema_de_quests.scp

ajuste de queststate para questState na função quest_targCleanupPC( pcUID )

Ajuste mínimo

---

sphere_56b/trunk/scripts/myt/sistema_de_quests.scp

Teste de Trigger

---

sphere_56b/trunk/scripts/myt/itens_jewelry.scp

Correções baseadas na tabela de referência e resources:
Ref. 	Colar  Brinco  Bracelete
Cobre		-100	   50	    200       400
Bronze		 -50	  100	    250       450
Ferro		   00	  150	    300       500
Prata		+100  250    400       600
Ouro		+200  350    500       700
Obsid/Ebano	+300  450    600       800
Rubridium	+400  550    700       900
Mitril		+700  850   1000      1200
Eldasthar		+1000 1150   1300    1500

Ajuste de Durabilidade de t_jewelry

---

sphere_56b/trunk/scripts/myt/special/region.scp

-Alterado de 4% para 0 o rate de "nothing";
-Aumentado de 0.5% para 4.5% o rate de mithril.

Alteração do Regiontype
